spin_manifest_version = 2

[application]
authors = ["Antoni Dikov"]
name = "Yahoo Oracle"
version = "0.1.0"

[application.trigger.settings]
interval_time_in_seconds = 10
sequencer = "http://sequencer:8877/post_report"
secret_key = "536d1f9d97166eba5ff0efb8cc8dbeb856fb13d2d126ed1efc761e9955014003"
reporter_id = 0

[[trigger.oracle]]
component = "yahoo"

[[trigger.oracle.data_feeds]]
data = '{"yf_symbol":"EURUSD=X"}'
id = "253"

[[trigger.oracle.data_feeds]]
data = '{"yf_symbol":"BTC-USD"}'
id = "31"

[[trigger.oracle.data_feeds]]
data = '{"yf_symbol":"ETH-USD"}'
id = "47"

[[trigger.oracle.capabilities]]
data = "xfbfACKQNe2ibfIEuXt1q1uVgYHMnFjW6mENHC7V"
id = "YAHOO_API_KEY"

[component.yahoo]
source = "target/wasm32-wasi/release/yahoo_oracle.wasm"
allowed_outbound_hosts = [
  "https://yfapi.net:443",
]
[component.yahoo.build]
command = "cargo build --target wasm32-wasi --release"
